server
{
    #un fichier conf commence pas des info generales sur 
    #le serveur

    #identite du serveur
    #ou se trouve t il
    host 127.0.0.1;
    port 8002;
    
    #comment s appelle le serveur
    server_name localhost;

    #ou sont les fichier accesible aux serveurs
    root docs/fusion_web/;

    #max taille d une requette HTTP
    client_max_body_size 3000000;

    #premier visage du site quand on rentre
    index index.html;

    #pages d erreurs que je pense c est mieux de leur faire une rubrique a eux meme
    error_page 404 error_pages/404.html;

    #le / represente la racine 
    #en gros les regles qu on fait danns la racine sont mis partout
    location /
    {
        #on definie les methods aux quelles on a droit
        allow_methods  DELETE POST GET;
        #le autoindex off sert a que si on a pas de pages d accueil
        #normalement le serveur va montrer toutes les pages disponible
        #donc en mettant a off si on a pas de pages d accueil
        #le serveur va rien montrer
        autoindex off;
    }
    
    #c est des regles pour des pages specifique
    location /tours
    {
        autoindex on;
        index tours1.html;
        allow_methods GET POST PUT HEAD;
    }

    #regles pour pages /red specifique
	location /red
    {
		return /tours;
	}

    #regles poour pages specifique
    location /cgi-bin
    {
        root ./;
        allow_methods GET POST DELETE;
        index time.py;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
    }
}